version: '3'

services:
  python:
    image: local/pyquantum
    build:
      dockerfile: ./Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    environment:
      - DISPLAY=192.168.100.21:0.0
    tty: true
